[package]
name = "lipid"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
fs-err = "2.9.0"
hex = "0.4.3"
tabled = "0.14.0"
